config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#dashboard'
  resources :pages, only: :dashboard
  resources :orders, only: [:index, :edit, :update] do
    member do
      post :remove_from_load
      post :split
    end
  end
  resource :order_csv_uploader, only: [:new, :create]
  resources :loads do
    resources :orders, only: [] do
      post :move_up
      post :move_down
    end
  end
  resources :route_lists, only: [:index, :show]

end

app/controllers/route_lists_controller.rb
class RouteListsController < ApplicationController
  def index
    present RouteList::Index
    @route_lists = @model
  end

  def show
    present RouteList::Show
    @route_list = @model
    @waypoints = @route_list.orders

    respond_to do |format|
      format.html
      format.pdf do
        file_name = "route list for #{@route_list.delivery_shift} #{@route_list.delivery_date}"
        render pdf: file_name,
               layout: 'pdf_layout.html.slim',
               encoding: 'utf8',
               orientation: 'Landscape',
               disposition: 'attachment'
      end
    end
  end

  private

  def process_params!(params)
    params.merge!(current_user: current_user)
  end
end

app/views/route_lists/_show.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-md-4
        h2 Route list for #{@route_list.delivery_date}, #{@route_list.delivery_shift}
      .col-md-offset-7.col-md-1
        = link_to 'Download', route_list_path(@route_list, format: :pdf),
                                           class: 'btn btn-primary btn-vertical-align'
  .panel-body
    table.table.table-striped.table-hover
      thead
        tr
          th №
          th Address
          th Order №
          th Phone
          th Cargo info
      tbody
        - if @route_list.orders_count > 0
          tr
            td 1
            td colspan='4' Larkin LLC, starting
          - @waypoints.each_with_index do |order, idx|
            tr
              td = idx + 2
              td = address_string(order)
              td = order.purchase_order_number
              td = contacts_string(order)
              td = load_cargo_string(order)

          tr
            td = @route_list.orders_count + 2
            td colspan='4' Larkin LLC, returning

  .panel-footer
    = link_to 'Back', route_lists_path, class: 'btn btn-primary'

app/views/route_lists/index.html.slim
.panel.panel-default
  .panel-heading
    h2 Routes list
  .panel-body
    table.table.table-striped.table-hover
      thead
        tr
          th Delivery date
          th Delivery shift
          th colspan='2'Truck
      tbody
        .text-center
          = paginate @route_lists
        - @route_lists.each do |route_list|
          tr
            td = route_list.delivery_date
            td = route_list.delivery_shift
            td Truck №#{route_list.truck&.id}
            td.actions-column
              .btn-group
                = link_to 'Show', route_list_path(route_list), class: 'btn btn-default'
                = link_to 'Download', route_list_path(route_list, format: :pdf), class: 'btn btn-default'

app/views/route_lists/show.html.slim
= render 'show'

app/views/route_lists/show.pdf.slim
= render partial: 'show.html.slim'