config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#dashboard'
  resources :pages, only: :dashboard
  resources :orders, only: [:index, :edit, :update] do
    member do
      post :remove_from_load
      post :split
    end
  end
  resource :order_csv_uploader, only: [:new, :create]
  resources :loads do
    resources :orders, only: [] do
      post :move_up
      post :move_down
    end
  end
  resources :route_lists, only: [:index, :show]

end

app/models/load.rb
class Load < ActiveRecord::Base
  belongs_to :truck

  has_many :orders, -> { order(delivery_order: :ASC) }, dependent: :nullify

  scope :seen_by_driver, ->(driver) { joins(:truck).where(trucks: { user_id: driver.id }) }

  scope :by_date_and_shift, (lambda do
    order('delivery_date DESC',
          "(case delivery_shift when 'E' then 0 when 'N' then 1 when 'M' then 2 end) ASC")
  end)
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  def index
    present Load::Index
    @loads = @model
  end

  def show
    present Load::Show
    @load = @model
    @waypoints = @load.orders
  end

  def new
    form Load::Create
  end

  def create
    run Load::Create do |op|
      return redirect_to op.model
    end
    render :new
  end

  def edit
    form Load::Update
  end

  def update
    run Load::Update do |op|
      return redirect_to op.model
    end
    render :edit
  end

  def destroy
    run Load::Destroy do
      flash[:notice] = 'Load was successfully deleted.'
      return redirect_to loads_url
    end

    flash[:alert] = "Load wasnt't deleted."
    redirect_to loads_url
  end

  private

  def process_params!(params)
    params.merge!(current_user: current_user)
  end
end

app/views/loads/_form.html.slim
= simple_nested_form_for @form do |f|
  = f.error_notification

  = f.input :delivery_shift, as: :radio_buttons,
                             collection: Order::DELIVERY_SHIFTS

  = f.input :delivery_date, html5: true,
                            input_html: { value: f.object.delivery_date || Date.current}
  = f.input :truck_id, as: :select,
                       collection: Truck.pluck(:id),
                       label_method: lambda { |x| "Truck №#{x}"}

  .form-group
    = f.fields_for :orders do |order|
      - if order.object.id
        .row
          .col-md-8
            = order.input :order
              '
              = order_label_for_load(order.object)
          .col-md-4
            = order.link_to_remove "Remove this order", class: 'btn btn-warning'
      - else
        .row
          .col-md-8
            = order.input :id, as: :select,
                               collection: Order.undelivered.with_shift_order.map {|x| [x.id, order_label_for_load(x)]} ,
                               label_method: :last,
                               value_method: :first,
                               label: 'Order'
          .col-md-4.remove-link-vertical-align
            = order.link_to_remove "Remove this order", class: 'btn btn-warning'
    = f.link_to_add "Add an order", :orders, class: 'btn btn-default'

  .form-group
    = f.submit 'Submit', class: 'btn btn-success'

app/views/loads/edit.html.slim
.panel.panel-default
  .panel-heading
    h1 Edit Load

  .panel-body
    = render 'form'

  .panel-footer
    = link_to 'Back', loads_path, class: 'btn btn-primary'

app/views/loads/index.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-md-1
        h2 Loads
      .col-md-offset-10.col-md-1
        = link_to 'New Load', new_load_path, class: 'btn btn-primary btn-vertical-align'
  .panel-body
    table.table.table-striped.table-hover
      thead
        tr
          th Delivery date
          th Delivery shift
          th colspan='2' Truck
      tbody
        .text-center
          = paginate @loads
        - @loads.each do |load|
          tr
            td = load.delivery_date
            td = load.delivery_shift
            td = "Truck №#{load.truck.id}"
            td.actions-column
              .btn-group
                = link_to 'Edit', edit_load_path(load), class: 'btn btn-default'
                = link_to 'Route plan', load_path(load), class: 'btn btn-default'
                = link_to 'Delete', load_path(load), class: 'btn btn-danger',
                                                                  method: :delete,
                                                                  data: { confirm: "Are you sure?" }

app/views/loads/new.html.slim
.panel.panel-default
  .panel-heading
    h1 New Load

  .panel-body
    = render 'form'

  .panel-footer
    = link_to 'Back', loads_path, class: 'btn btn-primary'

app/views/loads/show.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-md-4
        h2 Load #{@load.delivery_date}, #{@load.delivery_shift}
      .col-md-offset-7.col-md-1
        = link_to 'Edit Load', edit_load_path(@load), class: 'btn btn-primary btn-vertical-align'
  .panel-body
    table.table.table-striped.table-hover
      thead
        tr
          th №
          th Address
          th Volume
          th colspan='3' Cargo info
      tbody
        - if @load.orders_count > 0
          tr
          - @waypoints.each_with_index do |order, idx|
            tr
              td = idx + 1
              td = address_string(order)
              td = order.volume
              td = load_cargo_string(order)
              td
                = link_to load_order_move_up_path(load_id: @load.id, order_id: order.id), method: :post
                  span.glyphicon.glyphicon-arrow-up
              td
                = link_to load_order_move_down_path(load_id: @load.id, order_id: order.id), method: :post
                  span.glyphicon.glyphicon-arrow-down
  .panel-footer
    = link_to 'Back', loads_path, class: 'btn btn-primary'