config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#dashboard'
  resources :pages, only: :dashboard
  resources :orders, only: [:index, :edit, :update] do
    member do
      post :remove_from_load
      post :split
    end
  end
  resource :order_csv_uploader, only: [:new, :create]
  resources :loads do
    resources :orders, only: [] do
      post :move_up
      post :move_down
    end
  end
  resources :route_lists, only: [:index, :show]

end

app/models/order.rb
class Order < ActiveRecord::Base
  DELIVERY_SHIFTS = %w(M N E).freeze

  belongs_to :load, counter_cache: true

  scope :with_shift_order, (lambda do
    order('coalesce(delivery_date) ASC NULLS FIRST',
          "(case delivery_shift when 'E' then 0 when 'N' then 1 when 'M' then 2 else -1 end) DESC",
          'destination_address')
  end)

  scope :scheduled, (lambda do |value|
    if value == 'true'
      where.not(load_id: nil)
    elsif value == 'false'
      undelivered
    end
  end)

  scope :undelivered, -> { where(load_id: nil) }

  scope :by_deliry_order, -> { order('delivery_order ASC NULLS LAST') }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    present Order::Index
    @orders = @model
  end

  def edit
    form Order::Update
  end

  def update
    run Order::Update do
      flash[:notice] = 'Order was successfully updated.'
      return redirect_to orders_url
    end

    render :edit
  end

  def split
    run Order::Split do
      flash[:notice] = 'Order was successfully splitted.'
      return redirect_to orders_url
    end

    flash[:alert] = "Order cannot be splitted. #{@form.errors.full_messages.to_sentence}"
    redirect_to orders_url
  end

  def remove_from_load
    run Order::RemoveFromLoad do
      flash[:notice] = 'Order was successfully removed from the Load.'
      return redirect_to orders_url
    end

    flash[:alert] = 'Order not in the Load.'
    redirect_to orders_url
  end

  def move_up
    operation = Load::DecreaseDeliveryOrder.run(id: params[:load_id],
                                                order_id: params[:order_id],
                                                current_user: current_user) do
      return redirect_to load_url(id: params[:load_id])
    end
    flash[:alert] = "Delivery order was not changed. #{operation.errors.full_messages.to_sentence}"
    redirect_to load_url(id: params[:load_id])
  end

  def move_down
    operation = Load::IncreaseDeliveryOrder.run(id: params[:load_id],
                                                order_id: params[:order_id],
                                                current_user: current_user) do
      return redirect_to load_url(id: params[:load_id])
    end
    flash[:alert] = "Delivery order was not changed. #{operation.errors.full_messages.to_sentence}"
    redirect_to load_url(id: params[:load_id])
  end

  private

  def process_params!(params)
    params.merge!(current_user: current_user)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_label_for_load(order)
    label = "#{order.delivery_date}, #{order.delivery_shift}"
    if order.returning
      label << " #{order.origin_address}, #{order.origin_city}"
      label << ", #{order.origin_state}, #{order.origin_zip}"
    else
      label << " #{order.destination_address}, #{order.destination_city}"
      label << ", #{order.destination_state}, #{order.destination_zip}"
    end
    label << "#{order.handling_unit_quantity}, #{order.handling_unit_type}, #{order.volume}"
    label << ', Return' if order.returning
    label
  end

  def address_string(order)
    if order.returning
      "#{order.origin_address}, #{order.origin_city}, #{order.origin_state}, #{order.origin_zip}"
    else
      "#{order.destination_address}, #{order.destination_city}, "\
      "#{order.destination_state}, #{order.destination_zip}"
    end
  end

  def load_cargo_string(order)
    return unless order.handling_unit_quantity && order.handling_unit_type

    verb = order.returning ? 'load ' : 'unload '
    verb + cargo_string(order)
  end

  def cargo_string(order)
    return unless order.handling_unit_quantity && order.handling_unit_type
    pluralize(order.handling_unit_quantity, order.handling_unit_type)
  end

  def route_list_address_string(order)
    if order.returning
      "#{order.origin_address}, #{order.origin_city}, #{order.origin_state}, #{order.origin_zip}"
    else
      "#{order.destination_address}, #{order.destination_city}, "\
      "#{order.destination_state}, #{order.destination_zip}"
    end
  end

  def contacts_string(order)
    client_name = order.returning ? order.origin_name : order.client_name
    "#{client_name},  #{order.phone_number}"
  end

  def order_row_style(order)
    if order.load_id
      'info'
    elsif order.returning
      'warning'
    elsif danger_order?(order)
      'danger'
    end
  end

  def danger_order?(order)
    order.handling_unit_quantity.blank? ||
      order.handling_unit_quantity.zero? ||
      order.volume.blank? ||
      order.volume.zero? ||
      order.delivery_date.blank?
  end
end

app/views/orders/edit.html.slim
.panel.panel-default
  .panel-heading
    h1 Edit Order

  .panel-body
    = simple_form_for @form do |f|
      = f.error_notification

      .row
        .col-md-2
          .form-group
            = f.input :delivery_shift, as: :radio_buttons,
                                       collection: Order::DELIVERY_SHIFTS
          .form-group
            = f.input :delivery_date, as: :date, html5: true

        .col-md-5
          = f.input :origin_name
          = f.input :origin_address
          = f.input :origin_city
          = f.input :origin_state
          = f.input :origin_zip
          = f.input :origin_country, as: :string
        .col-md-5
          = f.input :destination_address
          = f.input :destination_city
          = f.input :destination_state
          = f.input :destination_zip
          = f.input :destination_country, as: :string
      .row
        .col-md-6
          = f.input :client_name
          = f.input :phone_number
          = f.input :purchase_order_number
        .col-md-6
          = f.input :mode
          = f.input :volume
          = f.input :handling_unit_quantity
          = f.input :handling_unit_type

      .form-group
        = f.submit 'Submit', class: 'btn btn-success'

  .panel-footer
    = link_to 'Back', orders_path, class: 'btn btn-primary'

app/views/orders/index.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-md-1
        h2 Orders
      .col-md-offset-8.col-md-3
        .btn-group
          = link_to 'All', orders_path, class: 'btn btn-default btn-vertical-align'
          = link_to 'Scheduled', orders_path(scheduled: true), class: 'btn btn-default btn-vertical-align'
          = link_to 'Not scheduled', orders_path(scheduled: false), class: 'btn btn-default btn-vertical-align'
  .panel-body
    table.table.table-striped.table-hover
      thead
        tr
          th Delivery date
          th Delivery shift
          th Order №
          th Client name
          th Phone
          th Address
          th City
          th State
          th Units
      tbody
        .text-center
          = paginate @orders
        - @orders.each do |order|
          tr class=order_row_style(order)
            td = order.delivery_date
            td = order.delivery_shift
            td = order.purchase_order_number
            - if order.returning
              td = order.origin_name
              td = order.phone_number
              td = order.origin_address
              td = order.origin_city
              td = order.origin_state
            - else
              td = order.client_name
              td = order.phone_number
              td = order.destination_address
              td = order.destination_city
              td = order.destination_state
            td = cargo_string(order)
            td.actions-column
              .btn-group
                = link_to 'Edit', edit_order_path(order), class: 'btn btn-default'
                = link_to 'Split', split_order_path(order), method: :post, class: 'btn btn-warning'
                = link_to 'Unload', remove_from_load_order_path(order), method: :post, class: 'btn btn-danger', data: { confirm: "Are you sure?" }