config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#dashboard'
  resources :pages, only: :dashboard
  resources :orders, only: [:index, :edit, :update] do
    member do
      post :remove_from_load
      post :split
    end
  end
  resource :order_csv_uploader, only: [:new, :create]
  resources :loads do
    resources :orders, only: [] do
      post :move_up
      post :move_down
    end
  end
  resources :route_lists, only: [:index, :show]

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = Lrkn
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          = link_to "Larkin LLC", root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          .nav.navbar-nav
            - if current_user_dispatcher?
              li = link_to 'Upload orders', new_order_csv_uploader_path
              li = link_to 'Orders', orders_path
              li = link_to 'Loads', loads_path
            - if user_signed_in?
              li = link_to 'Routes list', route_lists_path
          .nav.navbar-nav.navbar-right
            - if user_signed_in?
              li = link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              li = link_to 'Sign in', new_user_session_path
    .container-fluid
      div
        - flash.each do |name, msg|
          - errors_keys = ['error', 'alert']
          = content_tag :div,
                        class: "alert alert-#{ errors_keys.include?(name) ? "danger" : "success" } alert-dismissable alert-flash",
                        role: "alert"  do
            button.close type="button" data-dismiss="alert"
              span
                | &times;
            == msg
      .row
        .col-md-12
          = yield

app/views/layouts/pdf_layout.html.slim
doctype html
html
  head
    title = Lrkn
    = wicked_pdf_stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track' => true
  body
    .row
      .col-md-12
        = yield